---
name: iris-marketplace-web-app-prod
services:
  app:
    container_name: iris-marketplace-web-app-prod-c
    image: iris-marketplace-web-app-prod-i:2.0
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8025:80'
# docker image tag iris-marketplace-web-app-prod-i:2.0 silveira42/iris-marketplace-web-app:2.0
# docker image tag iris-marketplace-web-app-prod-i:2.0 silveira42/iris-marketplace-web-app:latest
# docker push silveira42/iris-marketplace-web-app:2.0
# docker push silveira42/iris-marketplace-web-app:latest
